---
# Late Dirctory Setup. Mainly for docker mode.
- name: Create Config Directories.
  ansible.builtin.file:
    state: directory
    mode: "{{ config_dir.mode | default('0755') }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    path: "{{ config_dir }}"
  loop: "{{ haproxy_config_dirs }}"
  loop_control:
    loop_var: config_dir

- name: Find out if the haproxy_dhparams_file exists.
  ansible.builtin.stat:
    path: "{{ haproxy_dhparams_file }}"
  register: haproxy_dhaparams_file_stat
  when: haproxy_dhparams_create | bool

- name: Create dhparams File.
  ansible.builtin.command: "openssl dhparam -out {{ haproxy_dhparams_file }} {{ haproxy_dhparams_bits }}"
  when:
    - haproxy_dhparams_create | bool
    - not haproxy_dhaparams_file_stat.stat.exists

- name: Template Error Pages.
  ansible.builtin.template:
    src: "errorpage.http.j2"
    dest: "{{ haproxy_errors_dir }}/{{ error_file.state }}.http"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: "0644"
  loop: "{{ haproxy_error_files }}"
  diff: "{{ haproxy_show_template_diffs }}"
  notify: "Haproxy Reload"
  loop_control:
    loop_var: error_file

- name: Copy LUA Files.
  ansible.builtin.copy:
    src: "lua/{{ lua_file }}"
    dest: "{{ haproxy_lua_dir }}/{{ lua_file }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: "0644"
  loop: "{{ haproxy_lua_files }}"
  notify: "Haproxy Reload"
  loop_control:
    loop_var: lua_file

- name: Template Configmaps.
  ansible.builtin.template:
    src: "configmap.map.j2"
    dest: "{{ haproxy_maps_dir }}/{{ config_map | flatten | first }}.map"
    mode: "0644"
  loop: "{{ haproxy_config_maps }}"
  diff: "{{ haproxy_show_template_diffs }}"
  notify: "Haproxy Reload"
  loop_control:
    loop_var: config_map

- name: Template haproxy.cfg.
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "{{ haproxy_config_dir }}/{{ haproxy_config_file }}"
    mode: "0644"
    validate: "{{ haproxy_validation_command }}"
  diff: "{{ haproxy_show_template_diffs }}"
  notify:
    - "Haproxy Reload"
    - "Haproxy Docker Reload"
...
