---
- name: "Output OS Environment."
  ansible.builtin.debug:
    msg:
      - "ansible_distribution:               {{ ansible_distribution }}"
      - "ansible_distribution_release:       {{ ansible_distribution_release }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_os_family:                  {{ ansible_os_family }}"
  when: haproxy_show_debug | bool

- name: "Set haproxy_version from default haproxy_version_defaults."
  ansible.builtin.set_fact:
    haproxy_version: "{{ haproxy_version_defaults[ansible_distribution | lower][(ansible_distribution_release or ansible_distribution_major_version) | lower | split | last] | default('unknown') }}"
  when: haproxy_version is undefined

- name: "Fail if haproxy_version is not known."
  ansible.builtin.fail:
    msg: "Was not able to determine the HAProxy version from defaults. Please set the variable haproxy_version yourself."
  when:
    - haproxy_version == "unknown"

- name: "Set haproxy_version_slug."
  ansible.builtin.set_fact:
    haproxy_version_slug: "{{ haproxy_version | regex_replace('\\.', '-') }}"

- name: "Set short name for more complicated Release Names."
  ansible.builtin.set_fact:
    ansible_distribution_release_shortname: "{{ ansible_distribution_release | lower | split(' ') | last }}"
  when: haproxy_installer is undefined

- name: "Show HAProxy versions."
  ansible.builtin.debug:
    msg:
      - "haproxy_version:      {{ haproxy_version }}"
      - "haproxy_version_slug: {{ haproxy_version_slug }}"
  when: haproxy_show_debug | bool

- name: "Set haproxy_installer."
  ansible.builtin.set_fact:
    haproxy_installer: "{{ haproxy_versions[ansible_distribution][ansible_distribution_release or ansible_distribution_major_version][haproxy_version_slug] }}"
  when: haproxy_versions[ansible_distribution][ansible_distribution_release or ansible_distribution_major_version][haproxy_version_slug] is defined

- name: "Set shortname for more complicated Release Names."
  ansible.builtin.set_fact:
    ansible_distribution_release_shortname: "{{ ansible_distribution_release | lower | split(' ') | last }}"
  when: haproxy_installer is undefined

- name: "Set haproxy_installer for more complicated Release Names."
  ansible.builtin.set_fact:
    haproxy_installer: "{{ haproxy_versions[ansible_distribution][ansible_distribution_release_shortname][haproxy_version_slug] }}"
  when:
    - haproxy_installer is undefined
    - haproxy_versions[ansible_distribution][ansible_distribution_release_shortname][haproxy_version_slug] is defined

- name: "Fail if haproxy_version is unsupported."
  ansible.builtin.fail:
    msg: "haproxy_version {{ haproxy_version }} is unsupported for {{ ansible_distribution_release }}"
  when: haproxy_installer is undefined
...
