---
- name: Check for SELinux Config File.
  ansible.builtin.stat:
    path: "/etc/selinux/config"
  register: haproxy_selinux_config_file_stat
  when: haproxy_selinux_enabled | bool

- name: Enable SELinux.
  ansible.builtin.command: "selinux-activate"
  register: haproxy_selinux_activated
  when:
    - haproxy_selinux_enabled | bool
    - not haproxy_selinux_config_file_stat.stat.exists

- name: Restart the System if needed.
  ansible.builtin.reboot:
  when:
    - haproxy_selinux_enabled | bool
    - haproxy_selinux_activated.changed

- name: Allowing HAProxy to listen on some TCP ports.
  community.general.seport:
    ports: "{{ haproxy_selinux_ports }}"
    proto: tcp
    setype: tor_port_t
    state: present
  when: haproxy_selinux_enabled | bool

- name: Enabling SELinux booleans for HAProxy.
  ansible.posix.seboolean:
    name: "{{ selinux_flag.name }}"
    state: "{{ selinux_flag.state | bool }}"
    persistent: true
  loop: "{{ haproxy_selinux_flags }}"
  when: haproxy_selinux_enabled | bool
  loop_control:
    loop_var: selinux_flag

- name: Firewalld set open Ports.
  ansible.posix.firewalld:
    port: "{{ firewalld_port }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ haproxy_firewalld_ports }}"
  loop_control:
    loop_var: firewalld_port
  when:
    - haproxy_firewalld_enabled | bool
    - haproxy_firewalld_ports | length > 0

- name: Set Sysctl Settings.
  ansible.posix.sysctl:
    name: "{{ sysctl_setting.name }}"
    value: "{{ sysctl_setting.value }}"
    sysctl_set: "{{ sysctl_setting.sysctl_set | default(false) }}"
    reload: "{{ sysctl_setting.reload | default(true) }}"
    state: "{{ sysctl_setting.state | default('present') }}"
  loop: "{{ haproxy_sysctl_settings }}"
  loop_control:
    loop_var: sysctl_setting
  when:
    - haproxy_sysctl_enabled | bool
    - haproxy_sysctl_settings | length > 0

- name: Setup Scripts Directory.
  ansible.builtin.file:
    path: "{{ haproxy_helper_scripts_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
  when: haproxy_helper_scripts_enabled | bool

- name: Install Helper Script Packages.
  ansible.builtin.package:
    name: "{{ haproxy_helper_scripts_packages }}"
  when: haproxy_helper_scripts_enabled | bool

- name: Template Helper Scripts.
  ansible.builtin.template:
    src: "{{ helper_script.src }}"
    dest: "{{ haproxy_helper_scripts_dir }}/{{ helper_script.name }}"
    mode: "{{ helper_script.mode | default('0755') }}"
  loop: "{{ haproxy_helper_scripts }}"
  loop_control:
    loop_var: helper_script
  diff: "{{ haproxy_show_template_diffs }}"
  when: haproxy_helper_scripts_enabled | bool

- name: Install packages to speed up entropy generation.
  ansible.builtin.package:
    name: "{{ haproxy_dhparams_packages }}"
  when:
    - haproxy_dhparams_create | bool
    - haproxy_dhparams_speedup | bool

- name: Template Logrotating Settings.
  ansible.builtin.template:
    src: "{{ logrotate_setting.src }}"
    dest: "{{ logrotate_setting.dest }}"
    mode: "{{ logrotate_setting.mode | default('0644') }}"
    owner: "{{ logrotate_setting.owner | default('root') }}"
    group: "{{ logrotate_setting.group | default('root') }}"
  diff: "{{ haproxy_show_template_diffs }}"
  loop:
    - src: "haproxy_logrotate.j2"
      dest: "/etc/logrotate.d/haproxy"
    - src: "haproxy_rsyslog.conf.j2"
      dest: "/etc/rsyslog.d/49-haproxy.conf"
  loop_control:
    loop_var: logrotate_setting
  when: haproxy_config_logrotate | bool
...
