---
- name: Haproxy Reload
  ansible.builtin.service:
    name: "{{ haproxy_service_name }}"
    state: reloaded
  when:
    - haproxy_mode == "system"
    - not haproxy_molecule_test

- name: Haproxy Docker Reload
  ansible.builtin.command: "docker kill -s USR2 {{ haproxy_docker_container_name }}"
  when:
    - haproxy_mode == "docker"
    - haproxy_docker_compose | bool

- name: Haproxy Docker Restart
  ansible.builtin.command: "docker compose up --force-recreate -d"
  args:
    chdir: "{{ haproxy_docker_dir }}"
  when:
    - haproxy_mode == "docker"
    - haproxy_docker_compose | bool

- name: "MOLECULE - Restart Apache (RedHat family)"
  ansible.builtin.command: "httpd -k restart"
  when:
    - haproxy_molecule_test | bool
    - ansible_os_family == "RedHat"
  listen: "Apache Restart"

- name: "MOLECULE - Restart Apache (Debian family)"
  ansible.builtin.service:
    name: apache2
    state: restarted
  when:
    - haproxy_molecule_test | bool
    - ansible_os_family == "Debian"
  listen: "Apache Restart"

- name: "Restart Apache service."
  ansible.builtin.service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted
  when:
    - not haproxy_molecule_test | bool
  listen: "Apache Restart"
...
