---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  # https://wiki.debian.org/DebianReleases
  - name: debian13
    image: debian:13-slim
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: debian12
    image: debian:12-slim
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: debian11
    image: debian:11-slim
    command: sleep infinity
    groups: [Debian]
    privileged: false
  # https://wiki.ubuntu.com/Releases
  # - name: ubuntu26.04
  #   image: ubuntu:24.04
  #   command: sleep infinity
  #   groups: [Debian]
  #   privileged: false
  - name: ubuntu24.04
    image: ubuntu:24.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: ubuntu22.04
    image: ubuntu:22.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: ubuntu20.04
    image: ubuntu:20.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  # https://wiki.rockylinux.org/rocky/version/?h=releases#current-supported-releases
  - name: rockylinux10.1
    image: rockylinux/rockylinux:10.1
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: rockylinux9.7
    image: rockylinux/rockylinux:9.7
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  # https://wiki.almalinux.org/release-notes/
  - name: almalinux10.1
    image: almalinux:10.1
    command: sleep infinity
    groups: [RedHat]
    privileges: false
  - name: almalinux9.7
    image: almalinux:9.7
    command: sleep infinity
    groups: [RedHat]
    privileged: false
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - create
    - converge
    # - idempotence
    - destroy
verifier:
  name: testinfra
  options:
    v: true
