---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  # https://wiki.debian.org/DebianReleases
  - name: debian12
    image: debian:12-slim
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: debian11
    image: debian:11-slim
    command: sleep infinity
    groups: [Debian]
    privileged: false
  # https://wiki.ubuntu.com/Releases
  - name: ubuntu24.04
    image: ubuntu:24.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: ubuntu22.04
    image: ubuntu:22.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  - name: ubuntu20.04
    image: ubuntu:20.04
    command: sleep infinity
    groups: [Debian]
    privileged: false
  # Rocky releases
  - name: rockylinux9
    image: rockylinux:9
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  # Alma releases
  - name: almalinux95
    image: almalinux:9.5
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: almalinux94
    image: almalinux:9.4
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: almalinux93
    image: almalinux:9.3
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: almalinux92
    image: almalinux:9.2
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: almalinux91
    image: almalinux:9.1
    command: sleep infinity
    groups: [RedHat]
    privileged: false
  - name: almalinux90
    image: almalinux:9.0
    command: sleep infinity
    groups: [RedHat]
    privileged: false
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - create
    - converge
    # - idempotence
    - destroy
verifier:
  name: testinfra
  options:
    v: true
