---
name: Anible Galaxy Publish
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v3
      - name: Ansible Role Publish.
        uses: 0x022b/galaxy-role-import-action@1.0.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          repository-owner: martin-micimo
          repository-name: haproxy
...
